name: Build macOS DMG

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      # 1. Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Install dependencies (root-level if needed)
      - name: Install root dependencies
        run: pnpm install

      # 5. Move into Electron app directory
      - name: Change directory to Electron app
        working-directory: apps/ui-tars
        run: |
          # 6. Install dependencies inside the app (optional if already installed at root)
          pnpm install

          # 7. Build frontend + Electron app
          npm run build && npx electron-forge make --platform=darwin --arch=x64

      # 8. Upload the DMG as an artifact
      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-dmg
          path: apps/ui-tars/out/make/**/*.dmg
